
on : [push]

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    name: A greeting job
    steps: 
      - name: Hello world action step
        id: hello
        uses: rus111/hello-world-docker-action@v1
        with:
          who-to-greet: 'rus111 the github actions learner'
      # use the output from the 'hello' step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
          
